export * from './utils/tag'
export { defaultConfig } from './defaultConfig'
export { renderLabel } from './renderLabel'
export { Sidebar } from './components/Sidebar'
export { CustomBadge } from './components/CustomBadge'
export { MDXBadges } from './components/MDXBadges'

export type { Badge, BadgeOrBadgeFn } from './types/Badge'
export type { Display } from './types/DisplayOption'
export type { TagBadgeParameters } from './types/TagBadgeParameters'
export type { TagPattern, TagPatterns } from './types/TagPattern'
